services:
  backend:
    container_name: backend
    build:
      context: ./Backend/app
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_URL: jdbc:postgresql://database:5432/photos_database
    volumes:
      - ./Backend/app/:/app
      - ./Files/:/files

  gateway:
    container_name: gateway
    build:
      context: ./Backend/gateway
      dockerfile: Dockerfile
      target: dev
    depends_on:
      - database
    ports:
      - 8081:8081
    environment:
      SECRET_KEY: RxtBeFg7yunnBFGwa8dYa8Q7CiUiTJVn
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_URL: r2dbc:postgresql://database:5432/user_database
      DATABASE_NAME: user_database

      ADMIN_UNAME: student
      ADMIN_PASSWORD: student
    volumes:
      - ./Backend/gateway/:/app

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./Frontend/:/app
      - /app/node_modules
      - /app/.next

  database:
    container_name: database
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: student
    volumes:
      - ./InitDatabase:/docker-entrypoint-initdb.d
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 5420:80
    environment:
      PGADMIN_DEFAULT_EMAIL: student@student.student
      PGADMIN_DEFAULT_PASSWORD: student
    


# docker run -e POSTGRES_PASSWORD=student -p 5432:5432 postgres
# docker run -e PGADMIN_DEFAULT_EMAIL=student@student.student -e PGADMIN_DEFAULT_PASSWORD=student -p 5420:80 dpage/pgadmin4