CREATE DATABASE user_database;

\c user_database;

CREATE TABLE IF NOT EXISTS public.user_db (
  id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY, 
  username VARCHAR(255) NOT NULL UNIQUE, 
  password VARCHAR(255) NOT NULL,
  isAdmin BOOLEAN NOT NULL DEFAULT FALSE
);

INSERT INTO user_db(
  username, 
  password, 
  isadmin
) VALUES ('student', 'student', true);

INSERT INTO user_db(
  username, 
  password, 
  isadmin
) VALUES ('student1', 'student1', false);